resources:
- name: source-code
  type: git
  source:
    uri: https://gitcode.com/qicx/simple-python-app
    branch: main

jobs:
- name: hello-pipeline
  public: true

  plan:
  - get: source-code

  - task: git-show
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: registry.fedoraproject.org/fedora
          tag: "44"
      inputs:
      - name: source-code
      run:
        path: sh
        args:
        - -exc
        - |
          revision=$(git rev-parse HEAD)
          echo "build revision $revision"
          ls -l
          dnf install -y buildah

  - task: greeting
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: registry.fedoraproject.org/fedora
          tag: "44"
      run:
        path: sh
        args:
        - -exc
        - |
          printf "Hello from Concourse!\n"


# vim: ts=2 sw=2 ai eb
